# Generated by Django 5.1.3 on 2024-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="reminder_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время напоминания"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Действие"
            ),
        ),
    ]
